---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  steps:
    - name: npm-install
      image: node:16
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npm ci
    - name: npm-test
      image: node:16
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npm test || echo "no test"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: jasmine-tests
      image: node:16
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        npm install -g jasmine
        npx jasmine || npm run test:jasmine
